### ISSUE TITLE
How do we separate usertypes on Dashboard?

### ISSUE THREAD

**Issue by alexthemitchell** [CSC322-Grinnell/curricular-planning#44]
* SamR's account should be able to use editing features implemented in #43 and #37
* All student accounts should only be able to view the classes which will be offered

**Comment by maripot** [comment]
devise offers multiple model authentication - but we need to figure out the details 
http://stackoverflow.com/questions/7254734/devise-login-from-two-model

**Comment by alexthemitchell** [comment]
We also will need to adjust the information in the tables accordingly (i.e. Sam's view should not have course title, but students' should)

**Comment by maripot** [comment]
http://www.bicrement.com/articles/2014/multiple-models-in-devise.html
